### ISSUE TITLE
help needed: use pdf preview and regions selection in spring boot project with thymeleaf

### ISSUE THREAD

**Issue by iWhacko** [tabulapdf/tabula-web-java#2]
I'm trying to liberate the PDF-preview page and region selection from this project. Since I want to embed it in a project that does not use spark and very limited ajax/jquery.

therefore I would like to know if someone can help me with this, or has done this in the past.

**Comment by jazzido** [comment]
Hi @iWhacko,

The region selection is a Javascript component, so it *should* be possible to extract it from this or the official Tabula web app with a bit of effort.

PDF preview is implemented with PDFBox rendering.
